### ISSUE TITLE
Create a Contribution.md file

### ISSUE THREAD

**Issue by Sahil-kachhap** [CodeFlow201/forestTreesTagging#11]
- Although there is a project setup instructions in the Readme file. I would like to create a seperate file having all git commands to setup the project , and about project issues and creating a PR.

- if this seems to be legitimate. Do assign me with this issue.

**Comment by ghackg11** [comment]
@Sahil-kachhap yes you can work on that, I am assigning this issue to you, happy coding and all the best:)
