### ISSUE TITLE
Tech Stack Update ( LOGO add )

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [CodeFlow201/forestTreesTagging#16]
I will like to add tech stack logo used in our project this will make our project attractive !! Will start to work on this issue as soon as i get assigned !!

**Comment by ghackg11** [comment]
> I will like to add tech stack logo used in our project this will make our project attractive !! Will start to work on this issue as soon as i get assigned !!

are you talking about adding logos of the tech stack used in the readme.md file?

**Comment by rohan-kulkarni-25** [comment]
Yes

**Comment by ghackg11** [comment]
@rohank2502 okay, I am assigning this issue to you, all the best!

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> @rohank2502 okay, I am assigning this issue to you, all the best!

Will you please tell name of tech you will like to add !!
