### ISSUE TITLE
Email and Password Authentication with Registered Email Verification

### ISSUE THREAD

**Issue by SamarpanCoder2002** [CodeFlow201/forestTreesTagging#19]
Hello, I want to add Email and Password Authentication with registered email verification through firebase with this app....

I have experience in that.... So I can do it perfectly.... Kindly assign me here, If I can proceed with that.....

I am also a gssoc'21 participant.... Please raise the required label for that program in that issue....

Please let me know If I can forward with that feature....

Thank You.....

**Comment by ghackg11** [comment]
@SamarpanCoder2002 you can start working on the issue, all the best

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002 you can start working on the issue, all the best

Thanks for assign me @ghackg11 ..... I will add the feature soon..... kindly add firebase account with my mail: samarpanofficial2021@gmail.com .... So that I can do email and password authentication with firebase...


If you want, I store user info in cloud firestore, Please give me the access of cloud firestore with firebase account......

**Comment by ghackg11** [comment]
@SamarpanCoder2002 Done.

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002 Done.

Thanks a lot @ghackg11 .... I will add this feature very soon.....

**Comment by ghackg11** [comment]
@SamarpanCoder2002 all the best:)

**Comment by STARLORD3** [comment]
@SamarpanCoder2002 can i work on the frontend part of this issue?

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002 can i work on the frontend part of this issue?

Actually my frontend part work already complete..... After my pull request merged, If You want you can redesign the UI of that with raise a new issue......But not now....because, my design almost complete...

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002 can i work on the frontend part of this issue?

Actually my frontend part already complete...after my pull request merged, If you want you can redesign UI of that

**Comment by SamarpanCoder2002** [comment]
Hello @ghackg11 , I already make a pull request regarding to that.....Please check it out

**Comment by ghackg11** [comment]
This issue is solved now by @SamarpanCoder2002, thank you for your contribution. I will make a new issue related to the frontend, thank you guys.

**Comment by ghackg11** [comment]
@SamarpanCoder2002 The signup is not working suddenly, can you please recheck it. My whole checking work is on pause due to that. It's a request that you look for it asap.

![WhatsApp Image 2021-03-19 at 2 02 55 PM](https://user-images.githubusercontent.com/56071613/111752829-2cb1a180-88bc-11eb-8388-6bb72a4bb353.jpeg)

**Comment by ghackg11** [comment]
hey @SamarpanCoder2002, The signup functionality stopped working, can you please have a look at it. It's very urgent. The whole work is at pause due to that.
![WhatsApp Image 2021-03-19 at 2 02 55 PM](https://user-images.githubusercontent.com/56071613/111753986-7c449d00-88bd-11eb-81d5-c96e83ea5f74.jpeg)

**Comment by SamarpanCoder2002** [comment]
> hey @SamarpanCoder2002, The signup functionality stopped working, can you please have a look at it. It's very urgent. The whole work is at pause due to that.

Yah sure... I try to solve it

**Comment by ghackg11** [comment]
> > hey @SamarpanCoder2002, The signup functionality stopped working, can you please have a look at it. It's very urgent. The whole work is at pause due to that.
> 
> Yah sure... I try to solve it

Thank you:)

**Comment by SamarpanCoder2002** [comment]
> > > hey @SamarpanCoder2002, The signup functionality stopped working, can you please have a look at it. It's very urgent. The whole work is at pause due to that.
> > 
> > 
> > Yah sure... I try to solve it
> 
> Thank you:)

I already make a pull request..please read the pull request description and try it...Thanks @ghackg11
