### ISSUE TITLE
Sign-Up Page

### ISSUE THREAD

**Issue by STARLORD3** [CodeFlow201/forestTreesTagging#21]
@ghackg11 I can also work on creating a signup page?

**Comment by Ruhika1417** [comment]
hi @STARLORD3  can i work on this?

**Comment by Ruhika1417** [comment]
hi @STARLORD3 can i work on this if its under gssoc'21 ?

**Comment by ghackg11** [comment]
@STARLORD3 @Ruhika1417  The login and signup are already being worked upon, you can have a look at other issues or you can create your own. Happy Coding:)

**Comment by Ruhika1417** [comment]
@STARLORD okay thank!!
