### ISSUE TITLE
Profile Picture in Home Page

### ISSUE THREAD

**Issue by SamarpanCoder2002** [CodeFlow201/forestTreesTagging#24]
Hello, I want to add profile picture on the home page of this app...

<img src="https://user-images.githubusercontent.com/66327336/111082324-a862c580-852d-11eb-92fd-682d469b8f2c.png" width="200">

If I can forward with that, please assign me to here..... I am also a gssoc'21 participant.......Waiting for your response... @ghackg11

**Comment by ghackg11** [comment]
@SamarpanCoder2002, yes you can work on that, I am assigning this issue to you.

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002, yes you can work on that, I am assigning this issue to you.

Thanks a lot @ghackg11 .... I will make a pull request related to that soon

**Comment by SamarpanCoder2002** [comment]
> > @SamarpanCoder2002, yes you can work on that, I am assigning this issue to you.
> 
> Thanks a lot @ghackg11 .... I will make a pull request related to that soon

I already make a pull request regarding to that..... Hope you review and merge it soon @ghackg11 ...... If there any problem, you can freely tell me.. Thanks @ghackg11
