### ISSUE TITLE
[Need] Issue and PR template

### ISSUE THREAD

**Issue by Aryamanz29** [CodeFlow201/forestTreesTagging#26]
Currently, we haven't any issue and PR template for this repo

**Comment by Aryamanz29** [comment]
Please add a label to this issue

**Comment by Aryamanz29** [comment]
I would like to work on this issue, Kindly assign to me

**Comment by ghackg11** [comment]
@Aryamanz29 Good to see you here! You can work on this issue, I am assigning this to you
