### ISSUE TITLE
Redesigning of login page

### ISSUE THREAD

**Issue by STARLORD3** [CodeFlow201/forestTreesTagging#29]
@ghackg11 can I redesign the login page?
the base of redesigning will be this page :- 
https://drive.google.com/file/d/1a4k5LsAhpGXPblBqJcjSth_BYQe0V2JA/view?usp=sharing

**Comment by ghackg11** [comment]
@STARLORD3 the design is nice, but can you make the color theme green? Just like the present app. It should have a consistent theme right?

**Comment by STARLORD3** [comment]
@ghackg11 for sure as it is just a base

**Comment by STARLORD3** [comment]
@ghackg11 we can add delete or do anything with it

**Comment by ghackg11** [comment]
Okay, you can start working on this, I am assigning this to you and adding labels to it. All the best:)

**Comment by STARLORD3** [comment]
Ok thanks

**Comment by STARLORD3** [comment]
can I also make an issue for the signup page?

**Comment by STARLORD3** [comment]
@ghackg11

**Comment by ghackg11** [comment]
Yes,@STARLORD3

**Comment by STARLORD3** [comment]
OK

**Comment by STARLORD3** [comment]
![image](https://user-images.githubusercontent.com/44573625/111512904-3e892c80-8776-11eb-8ebc-e0e5f2ae707b.png)
@ghackg11 is the login page looking fine?

**Comment by ghackg11** [comment]
Yeah that's great 👍

**Comment by STARLORD3** [comment]
@ghackg11 please check the PR
