### ISSUE TITLE
Updating the UI

### ISSUE THREAD

**Issue by ghackg11** [CodeFlow201/forestTreesTagging#3]
As you have already seen, we have made a pretty basic UI, which can be updated with some effort. Design inspirations are given in this link below, you can take help from this, or you can boggle your mind to think of innovative changes and implement them.

https://whimsical.com/foresttreetagger-QhpS4e7HyEaYXtQ23rP8AE

**Comment by Samdid** [comment]
@ghackg11 I would like to work on this

**Comment by Manzee1609** [comment]
I would like to work on this! :)

**Comment by Samdid** [comment]
@ghackg11 Can I start working on this issue?

**Comment by ghackg11** [comment]
> @ghackg11 Can I start working on this issue?

yes, you all can start working

**Comment by ghackg11** [comment]
> @ghackg11 Can I start working on this issue?

I am assigning this issue to you, you have a max of 5 days to work on it and send PRs

**Comment by STARLORD3** [comment]
@ghackg11 can I work  on this issue

**Comment by Samdid** [comment]
> > @ghackg11 Can I start working on this issue?
> 
> I am assigning this issue to you, you have a max of 5 days to work on it and send PRs

Okay

**Comment by ghackg11** [comment]
> @ghackg11 can I work  on this issue
> 

Yes you can

**Comment by STARLORD3** [comment]
@ghackg11 so I have to make these five screens with some of my ideas included in this project?

**Comment by ghackg11** [comment]
> @ghackg11 so I have to make these five screens with some of my ideas included in this project?

Not all 5 necessary, some part is already done in the app, u just have to make modifications in the UI/UX , and the given designs are for inspiration

**Comment by STARLORD3** [comment]
ok thanks

**Comment by STARLORD3** [comment]
@ghackg11 will there be any login/signup page to see the homepage?

**Comment by STARLORD3** [comment]
@ghackg11 if there will be any of these things  then I want to work on this

**Comment by pranavi79** [comment]
can i be assigned to this issue too?

**Comment by ghackg11** [comment]
> @ghackg11 will there be any login/signup page to see the homepage?

we are planning to have a login signup page, you will soon have designs for that, so you can start working on that asap, till then, you can work on other pages:)

**Comment by STARLORD3** [comment]
@ghackg11 can you please check the PR?
