### ISSUE TITLE
Redesigning of signup screen

### ISSUE THREAD

**Issue by STARLORD3** [CodeFlow201/forestTreesTagging#30]
@ghackg11 I will be redesigning the signup screen
The theme on which signup screen will be based is:-
https://drive.google.com/file/d/1a4k5LsAhpGXPblBqJcjSth_BYQe0V2JA/view?usp=sharing

**Comment by STARLORD3** [comment]
@ghackg11 please assign this to me and also please add the necessary tag to it

**Comment by ghackg11** [comment]
okay @STARLORD3, assigning this issue to you. All the best:)

**Comment by STARLORD3** [comment]
@ghackg11 please check the PR

**Comment by ghackg11** [comment]
I have reviewed and merged the PR. Thanks for your contribution, @STARLORD3
