### ISSUE TITLE
[Need] Workflow for GSSOC21 issue label

### ISSUE THREAD

**Issue by Aryamanz29** [CodeFlow201/forestTreesTagging#31]
### **Feature request**:
I want to add workflow which automatically adds `GSSOC21` label to new issues if they have  labels-synonyms: `'{"GSSOC21":["GSSOC","GSSOC21","gssoc","Gssoc","GSSoC"]}'`  in their `issue body`

![Screenshot from 2021-03-17 15-52-45](https://user-images.githubusercontent.com/56113566/111453959-209dd680-873a-11eb-93ca-37161f201192.png)

### **Is your feature request related to a problem? Please describe. (optional)**:
Yes it solves gssoc label issue which every time the maintainer has to do it manually

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by ghackg11** [comment]
@Aryamanz29, yes you can work on it. All the best:)

**Comment by Aryamanz29** [comment]
Kindly  review my PR @ghackg11
