### ISSUE TITLE
Add App Icon

### ISSUE THREAD

**Issue by Shubhrima** [CodeFlow201/forestTreesTagging#39]
### **Feature request**:
Add a new App Logo for the App.

### **Is your feature request related to a problem? Please describe. (optional)**:
The app uses the default Flutter Logo as its app Icon.

### **Describe the solution you'd like**:
I wish to change the Logo of the App from the default Flutter logo to a different image.

### **Describe how this feature will be useful to our readers**:
An effective logo is one that is instantly recognizable, and over time, becomes synonymous with the app. 

### **Additional context:**
![image](https://user-images.githubusercontent.com/68013183/111855366-7ba61800-894a-11eb-9f10-7c4a70c68bc3.png)

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by ghackg11** [comment]
@Shubhrima Would you design a logo for the app?

**Comment by Shubhrima** [comment]
Yes.

**Comment by ghackg11** [comment]
Okay @Shubhrima, U can continue with your work. I am assigning the issue to you.

**Comment by Shubhrima** [comment]
![image](https://user-images.githubusercontent.com/68013183/111952787-a8555d80-8b0b-11eb-89e7-3996d2e1dd95.png)

Does this look okay? Else what changes shall I do?

**Comment by ghackg11** [comment]
@Shubhrima, I think we are not syncing in our views regarding the logo design. We want a modern designed logo. You can take reference from the image I am attaching below.

https://www.seekpng.com/png/detail/19-190761_simple-location-map-pin-icon-location-pin-green.png. 

Try to make something like this.

**Comment by Shubhrima** [comment]
![image](https://user-images.githubusercontent.com/68013183/112035547-a9b37400-8b65-11eb-94dd-f4b8191c3146.png)

**Comment by ghackg11** [comment]
@Shubhrima, This one looks good, just remove the black borders from the green area.

**Comment by ghackg11** [comment]
Your PR is merged. Thank you for your contribution @Shubhrima .
