### ISSUE TITLE
Changing the design of the scanned tree list

### ISSUE THREAD

**Issue by ghackg11** [CodeFlow201/forestTreesTagging#40]
### **Feature request**:
Make the design of the tree scanning pages like the design in the picture below.

### **Describe how this feature will be useful to our readers**:
This will enhance the UI.

![WhatsApp Image 2021-03-21 at 12 29 34 PM](https://user-images.githubusercontent.com/56071613/111896705-77a8f180-8a41-11eb-91dc-3d4afdf094ee.jpeg)

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by Priya-81199** [comment]
I would like to work on this. GSSOC Participant.

**Comment by ghackg11** [comment]
@Priya-81199 , Yes you can work on it, I am assigning the issue to you. All the best:)

**Comment by Priya-81199** [comment]
Thank you so much! :)

**Comment by ghackg11** [comment]
@Priya-81199, It's been 4 days and I have no updates from your side. This issue shouldn't have taken so long.

**Comment by anotherwebguy** [comment]
i would like to work on this issue under gssoc plz assign me this issue @ghackg11  @vaibhavarora102 @vilsi12 @DARK-art108 @Sameerkash

**Comment by anotherwebguy** [comment]
is this fine should i make a pr now? @ghackg11 
![image](https://user-images.githubusercontent.com/66346161/114136896-0a45fd80-9929-11eb-8787-ca658793cb4e.png)
