### ISSUE TITLE
Designing the tree info page

### ISSUE THREAD

**Issue by ghackg11** [CodeFlow201/forestTreesTagging#41]
### **Feature request**:
Make the design of the Tree Info page and the wireframe for inspiration is given below.

### **Additional context:**
![WhatsApp Image 2021-03-21 at 12 29 34 PM (1)](https://user-images.githubusercontent.com/56071613/111896811-19c8d980-8a42-11eb-8e13-2e752bf8922e.jpeg)

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by STARLORD3** [comment]
@ghackg11 i can work on this issuue

**Comment by ghackg11** [comment]
@STARLORD3 , yes you can:) all the best

**Comment by STARLORD3** [comment]
@ghackg11 is the database working?

**Comment by STARLORD3** [comment]
sql one

**Comment by ghackg11** [comment]
@STARLORD3 , yes it is working

**Comment by ghackg11** [comment]
@STARLORD3 uninstall the app from your device and recheck.

**Comment by STARLORD3** [comment]
@ghackg11 can you please send the screenshot of the page after clicking the scan QR code of a tree button on the home screen.

**Comment by STARLORD3** [comment]
@ghackg11 because on my screen it is only showing open scanner and nothing else

**Comment by ghackg11** [comment]
![Screenshot_20210324-155157.jpg](https://user-images.githubusercontent.com/56071613/112295895-5e5eaa00-8cba-11eb-8790-84451a6f44c3.jpg)

**Comment by STARLORD3** [comment]
@ghackg11 i have also added details of a  new tree and saved the qr code

**Comment by ghackg11** [comment]
> ![Screenshot_20210324-155157.jpg](https://user-images.githubusercontent.com/56071613/112295895-5e5eaa00-8cba-11eb-8790-84451a6f44c3.jpg)

Scanned 3 trees in my app

**Comment by STARLORD3** [comment]
@ghackg11 ok i will now try to figure it out

**Comment by STARLORD3** [comment]
@ghackg11 thanks for the screenshot

**Comment by STARLORD3** [comment]
@ghackg11 if i recall correctly API key is not yet generated?

**Comment by ghackg11** [comment]
> @ghackg11 if i recall correctly API key is not yet generated?

Google map api key?

**Comment by STARLORD3** [comment]
yes @ghackg11

**Comment by ghackg11** [comment]
> yes @ghackg11 
> not yet

**Comment by STARLORD3** [comment]
@ghackg11 so what should i do for the map part of this design

**Comment by ghackg11** [comment]
@STARLORD3 use mapbox api, you can have static pins there

**Comment by STARLORD3** [comment]
@ghackg11 can you please provide the required credential i.e. token

**Comment by ghackg11** [comment]
@STARLORD3 use mapbox api, that is free of cost, you can get credentials there.

**Comment by STARLORD3** [comment]
Do I have to use the access token of my account

**Comment by ghackg11** [comment]
@STARLORD3 , yes, any problem regarding that?

**Comment by STARLORD3** [comment]
@ghackg11 is it right?
<img src = "https://user-images.githubusercontent.com/44573625/112524306-ae766300-8dc5-11eb-9af1-7b5c1422c796.png" height = 250, width = 120>

**Comment by ghackg11** [comment]
@STARLORD3 , yes it's good. Every component is fine. Can you make the design look a bit good?

**Comment by STARLORD3** [comment]
@STARLORD3 okay i can see into this

**Comment by STARLORD3** [comment]
@ghackg11 due to some problem i can not do the work for 15 days. Thus you can assign it to somebody else or u can close it.

**Comment by ghackg11** [comment]
@STARLORD3 ,did you send the pr of the work you have done yet?

**Comment by STARLORD3** [comment]
@ghackg11 sorry I forgot that i have not created a PR

**Comment by STARLORD3** [comment]
@ghackg11 either you can wait or assign it to somebody else.

**Comment by ghackg11** [comment]
@STARLORD3 ,If you can, you can create a pr for your work, so that your effort doesn't get wasted.

**Comment by STARLORD3** [comment]
@ghackg11 it will be not poasible for me.

**Comment by ghackg11** [comment]
@STARLORD3 , it's okay. I hope everything is fine.

**Comment by anotherwebguy** [comment]
Can i work on this issue under gssoc .plz assign me this issue @ghackg11 .

**Comment by anotherwebguy** [comment]
Hello @ghackg11 @vaibhavarora102 for this issue will u be giving me the api key needed for showing map with tree location on this app or should i generate my own api key and work on this issue?

**Comment by anotherwebguy** [comment]
Because if i have to generate the api key then u need to add me on firebase  as we have to add this app on console.google.com and enable google maps for it.
My email id mohitrajputms123@gmail.com

**Comment by anotherwebguy** [comment]
![image](https://user-images.githubusercontent.com/66346161/113871824-e8396780-97d0-11eb-95bb-565121091cc1.png)

i've designed the layout of treeinfo page just remains the map view for which i will be requiring the api key
BTW have a look at the layout is it good?

**Comment by anotherwebguy** [comment]
As u can see the steps to show map view in flutter
https://pub.dev/packages/google_maps_flutter
Will nees to enable map sdk for the app

**Comment by anotherwebguy** [comment]
![image](https://user-images.githubusercontent.com/66346161/113974127-09469a80-985b-11eb-8c32-63d5765de35d.png)

okay so i'm done with designing this page should i now make a pr ?
@ghackg11 @vaibhavarora102 @vilsi12

**Comment by vaibhavarora102** [comment]
Yeah for sure
