### ISSUE TITLE
The login functionality is not working properly.

### ISSUE THREAD

**Issue by Priya-81199** [CodeFlow201/forestTreesTagging#45]
### **Describe the bug:**
Whenever I try to login with the credentials, it doesn't navigate to the home screen and is stuck on the same page, after the hot reload it does navigate to the home screen as the login details are saved.

### **To Reproduce:**
1. Go to 'login page' and enter the credentials
2. Click on the 'login' button
3. See the error

### **Expected behavior:**
After the login button is clicked, it should navigate to the home screen.

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by ghackg11** [comment]
I have resolved it @Priya-81199 , please revert back after checking. There were no code changes required.

**Comment by Priya-81199** [comment]
Yes @ghackg11, I have checked it and now its working. Im closing this issue.

**Comment by ghackg11** [comment]
Thanks for raising the issue:)
