### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by abstrxtInfinity** [CodeFlow201/forestTreesTagging#48]
I have made a simple icon related to the application and would like to show it to you and if liked would like to implement the same in the application.

![tree-logo-design-template-abf440b5d98054b8bba87fba2205f19a_screen-removebg-preview](https://user-images.githubusercontent.com/55052738/112614375-33559100-8e47-11eb-9fd6-02a73c3ca0af.png)
![Copy of Tree Logo - Made with PosterMyWall](https://user-images.githubusercontent.com/55052738/112614381-3486be00-8e47-11eb-949c-d3f801bba6fb.png)

**Comment by ghackg11** [comment]
@abstrxtInfinity, Great efforts. It would be great if you add something related to tagging or QR code also in the app.

**Comment by anotherwebguy** [comment]
Well i've narraowed down some app icons have look if you'll like any of them then we can have that as the app icon @ghackg11 @vaibhavarora102 
![images (7)](https://user-images.githubusercontent.com/66346161/114217882-61c68680-9986-11eb-9f63-5a4fdea76de3.jpeg)
![images (6)](https://user-images.githubusercontent.com/66346161/114217887-62f7b380-9986-11eb-8555-bdd69d076f89.jpeg)
![pin-map-location-27-512](https://user-images.githubusercontent.com/66346161/114217890-63904a00-9986-11eb-84dc-1bdab4a6f7ff.png)
![forest-location-3235541-2703299](https://user-images.githubusercontent.com/66346161/114217891-6428e080-9986-11eb-84fc-77b743a18f98.png)

**Comment by ghackg11** [comment]
@anotherwebguy, I liked them, especially the third one, but are these open source/ free to use?

**Comment by anotherwebguy** [comment]
The third one is from iconfinder.com and i don't think anyone would have used that icon before @ghackg11

**Comment by ghackg11** [comment]
okay, I would like to discuss this with my team, before giving you any confirmation regarding this.

**Comment by anotherwebguy** [comment]
Yeah sure @ghackg11

**Comment by vaibhavarora102** [comment]
@anotherwebguy can you pls tell the sources of all the above logos, and kindly mention how it is customised by you

**Comment by anotherwebguy** [comment]
> @anotherwebguy can you pls tell the sources of all the above logos, and kindly mention how it is customised by you

Yes @vaibhavarora102 
Here they are
1)https://www.123rf.com/photo_103831987_stock-vector-tree-with-gps-icons-concept-illustration-about-travel-location-navigation-app-or-map-directions-vect.html
2)https://www.pinterest.com/pin/373587731562023213/?af_dp=pinterest%3A%2F%2F&pid=mweb&install_id=047b864c746446b6bc9e16ecbb7f11be&current_page_url=https://www.pinterest.com/amp/TMBPoole/qr-codes/&amp_client_id=ATF4ycWHUTehNQ7-par7PJoYYqcL0osq9M1yyYQ28KihDgPDBnZZqjqOCa-Nx16o&utm_source=168&shortlink=d4f1643&utm_medium=2166&deeplink_path=pinterest://pin/373587731562023213&amp_url=https://www.pinterest.com/amp/TMBPoole/qr-codes/&referrer=af_tranid%3DPH2p4OBHuho1H4BWbwjqmA%26af_r%3Dhttps%3A%2F%2Fwww.pinterest.com%2Fpin%2F373587731562023213%2F%26af_dp%3Dpinterest%253A%252F%252F%26pid%3Dmweb%26install_id%3D047b864c746446b6bc9e16ecbb7f11be%26current_page_url%3Dhttps%3A%2F%2Fwww.pinterest.com%2Famp%2FTMBPoole%2Fqr-codes%2F%26amp_client_id%3DATF4ycWHUTehNQ7-par7PJoYYqcL0osq9M1yyYQ28KihDgPDBnZZqjqOCa-Nx16o%26utm_source%3D168%26shortlink%3Dd4f1643%26utm_medium%3D2166%26af_web_id%3D9678a081-18aa-4574-b0f7-f5de4dd11eb4-o%26deeplink_path%3Dpinterest%3A%2F%2Fpin%2F373587731562023213%26amp_url%3Dhttps%3A%2F%2Fwww.pinterest.com%2Famp%2FTMBPoole%2Fqr-codes%2F
3)https://www.iconfinder.com/icons/1463998/forest_jungle_location_map_pin_tree_wild_icon
4)https://iconscout.com/icon/forest-location-3235541

**Comment by vaibhavarora102** [comment]
@anotherwebguy  thanks for putting efforts,
but we apologize that we cant use these logos, as it is not permitted according to Codeflow terms, I hope you understand
We can consider the logo that is wholly customized by you.
thanks

**Comment by anotherwebguy** [comment]
> @anotherwebguy thanks for putting efforts,
> but we apologize that we cant use these logos, as it is not permitted according to Codeflow terms, I hope you understand
> We can consider the logo that is wholly customized by you.
> thanks

Yeah i understand no wories altough i've never designed an app icon but i'll try to do it

**Comment by anotherwebguy** [comment]
hey @vaibhavarora102  @ghackg11  as u asked i've modified the app icon by adding some effects myself so now it's no more an copy![image](https://user-images.githubusercontent.com/66346161/114873842-57d6d480-9e19-11eb-9ca2-1ee21eb61a81.png)
##previous image

![Facebook Post 940x788 px (2) (1)](https://user-images.githubusercontent.com/66346161/114873909-691fe100-9e19-11eb-89f9-0b524e245f90.png)
##after editing

now if u will like this app icon we can take this as the project app icon
hope u'll reply soon

**Comment by ghackg11** [comment]
@anotherwebguy , it looks awesome 👌, great work!

**Comment by anotherwebguy** [comment]
So sir plz assign me this issue so that i could add this as the app icon for our app

**Comment by anotherwebguy** [comment]
Thanks for assigning me this issue i'll make a pr soon

**Comment by aman339** [comment]
I created these logo's too  for Forest tree Tagging. Have a look at these too.
![Group 8](https://user-images.githubusercontent.com/66405145/115002517-76dd7100-9ec2-11eb-8f52-ba2e8d836041.png)
![forest tree tagging4 (1)](https://user-images.githubusercontent.com/66405145/115002539-7c3abb80-9ec2-11eb-860e-47dae7a26e0d.png)
