### ISSUE TITLE
Save QR code button not working

### ISSUE THREAD

**Issue by ghackg11** [CodeFlow201/forestTreesTagging#5]
The save QR code button on this screen (In the link below) is not working. Some code is written but is buggy, so u need to fix it such that the QR code gets saved in PDF format in the local storage of the device.

![image](https://user-images.githubusercontent.com/56071613/110361916-a51b9580-8066-11eb-92dd-bce6000800ef.png)

**Comment by Trisanu-007** [comment]
Hi ! Can I try out this issue?

**Comment by ghackg11** [comment]
> Hi ! Can I try out this issue?

Yeah sure, it is open to everyone

**Comment by chakravarthi-v** [comment]
hey @ghackg11 I would like to work on this issue, I'm a GSSOC participant

**Comment by ghackg11** [comment]
> hey @ghackg11 I would like to work on this issue, I'm a GSSOC participant
> 

Sure, you have a maximum of 5 days for that, try to solve the issue in less than 3 days, which is the optimal time. I am assigning this to you and you can start working from now onwards.

**Comment by STARLORD3** [comment]
@ghackg11 can I work on this?

**Comment by chakravarthi-v** [comment]
> > hey @ghackg11 I would like to work on this issue, I'm a GSSOC participant
> 
> Sure, you have a maximum of 5 days for that, try to solve the issue in less than 3 days, which is the optimal time. I am assigning this to you and you can start working from now onwards.

okay sure :)

**Comment by akanksha470** [comment]
@ghackg11 can I try working on this issue?
I'm a GSSOC participant

**Comment by ghackg11** [comment]
> @ghackg11 can I try working on this issue?
> I'm a GSSOC participant

Yes you can:)

**Comment by STARLORD3** [comment]
@ghackg11 I am also a GSSOC participant

**Comment by ghackg11** [comment]
> @ghackg11 I am also a GSSOC participant

I have just assigned you another issue, first you can work on that

**Comment by chakravarthi-v** [comment]
Hey @ghackg11 , I have solved this issue do look into pull request #8  and let me know

**Comment by ghackg11** [comment]
@chakravarthi-v  You did a great job! We have solved this issue successfully so I am closing it now. All the best everyone for future contributions:)
