### ISSUE TITLE
Styling and Modifying the Readme.md file

### ISSUE THREAD

**Issue by DOOMSTERR** [CodeFlow201/forestTreesTagging#53]
## Request ✨
Hello sir, I want to modify the readme.md file.

## Detailed Description
I simply want to modify the heading by adding emojis to some headings and adding batches at the top-center to make it look more creative and beautiful:

I'll be adding 4 batches
-> issues-open
-> pull_request-open
-> total no. of forks
-> total no. of stars
 
@ghackg11 @vilsi12 @Sameerkash, please allow me to do so, by assigning me the issue under the GSSOC21 and Level label.

**Comment by ghackg11** [comment]
@DOOMSTERR, please resend the PR, we had to revert it due to some issue in the previous PR merged.

**Comment by DOOMSTERR** [comment]
ok
