### ISSUE TITLE
Adding google signin

### ISSUE THREAD

**Issue by anotherwebguy** [CodeFlow201/forestTreesTagging#66]
### **Feature request**:
Till now the app doesn't have a google signin feature. I would like to work on this feature

### **Describe the solution you'd like**:
I would like to connect the app with google authentication so that the user can login also through google accounts.

### **Describe how this feature will be useful to our readers**:
This signiin feature will be useful since it will save time which is being involved in the normal email auth verification.

<hr/>

Plz assign me this issue @ghackg11 @vaibhavarora102 under gssoc

Here's my email id u can add me on firebase :
mohitrajputms123@gmail.com

**Comment by ghackg11** [comment]
@anotherwebguy, yes you can work on it. All the best:)

**Comment by anotherwebguy** [comment]
> @anotherwebguy, yes you can work on it. All the best:)

Plz add me on the firebase for this @ghackg11 
My email
mohitrajputms123@gmail.com
