### ISSUE TITLE
Adding Code_Of_Conduct.md file

### ISSUE THREAD

**Issue by anotherwebguy** [CodeFlow201/forestTreesTagging#69]
# Prerequisites:

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I checked to make sure that this issue has not already been filed.

- [x] I'm reporting the issue to the correct repository (for multi-repository projects) **(optional)**

I feel This project must have an Code_Of_Conduct.md file

I would like to work on this issue under gssoc plz assign me this issue @ghackg11 @vaibhavarora102 @vilsi12 @Sameerkash @DARK-art108

**Comment by ghackg11** [comment]
@anotherwebguy, I see you are working on another two issues right now, you can work on this after you solve them. Its great to see hardworking people like you:)

**Comment by anotherwebguy** [comment]
Okay @ghackg11  i would like to work on this issue after i complete both the assigned issue first. Thanks :) . Hope u will assign it to me later
