### ISSUE TITLE
Forget Password Feature Not Added

### ISSUE THREAD

**Issue by SamarpanCoder2002** [CodeFlow201/forestTreesTagging#74]
### **Feature request**:
For Email and Password Auth, at Log-in, `Forget Password` Feature not added...I want to add it...

### **Is your feature request related to a problem? Please describe. (optional)**:
If user forget about password, they can reset it...

### **Describe the solution you'd like**:
When Click on `Forget Password`, a reset link will send to registed email....User Can Reset Mail from there

### **Describe alternatives you've considered**:
Mentioned Above

### **Describe how this feature will be useful to our readers**:
Mentioned Above

### **Additional context:**
As this navigation process, can't add anything

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. 

I am also a GSSOC21 particiapant...Please assign me to here with add the required labels for that program

**Comment by ghackg11** [comment]
@SamarpanCoder2002, Go ahead, try to work on it. all the best.

**Comment by SamarpanCoder2002** [comment]
Pull request Added @ghackg11 .... Please review it and merge it soon @ghackg11

**Comment by SamarpanCoder2002** [comment]
Hello @Sameerkash @ghackg11 ... I made changes according to you in that pull request( #78  )... Please review it and merge it

Made changes according to you @ghackg11 @Sameerkash .... Take a look
