### ISSUE TITLE
Adding Facebook auth

### ISSUE THREAD

**Issue by anotherwebguy** [CodeFlow201/forestTreesTagging#75]
### **Feature request**:
Adding Facebook authentication for users to signin
Also i'll take facebook profile picture to display as user image

### **Describe how this feature will be useful to our readers**:
This feature will be helpful for users how want to connect to the app through their socials

<hr/>

Plz assign me this issue @ghackg11 under gssoc as now i'am only working on one issue i.e #66 which will be resolved by me 1st thing in the morning

**Comment by ghackg11** [comment]
@anotherwebguy, adding Facebook auth to this app is not really required, as this is not meant for the general public. Just do one thing, use the Google account's image only and remake the PR.

**Comment by anotherwebguy** [comment]
> @anotherwebguy, adding Facebook auth to this app is not really required, as this is not meant for the general public. Just do one thing, use the Google account's image only and remake the PR.

Okay should i make another pr or continue with the same for google auth?
