### ISSUE TITLE
Refactoring profile image storing and retrieving method

### ISSUE THREAD

**Issue by anotherwebguy** [CodeFlow201/forestTreesTagging#81]
### **Feature request**:
Currently the app uses firebase storage bucket to store profile image of user and to retrieve image to display on home page.
Since this method takes two much time to load
I would like to suggest an better way to handle this

### **Is your feature request related to a problem? Please describe
The app takes too much time to load user's profile pic and also it's not the correct way to do it

### **Describe the solution you'd like**:
1)we will store all the user information in the firebase cloud storage in the user document
2) the user document will have following fields
a) name
b) email
c) profileimage
3)In this way we won't requide http package to first convert imageurl to file and then upload it to storage bucket
4)Using this method we can store and retrieve data quickly

<hr/>

Plz assign me this issue i would like to work on it
@Sameerkash @ghackg11 @vaibhavarora102 @vilsi12

**Comment by anotherwebguy** [comment]
I could work on this after pr #77 is merged right? @Sameerkash 
Bcoz i will be requiring to refactor all the places that uses the wrong method

**Comment by sameeerkashyap** [comment]
Yes, I don't have merge access, please reach out to the maintainer on discord.

**Comment by anotherwebguy** [comment]
> Yes, I don't have merge access, please reach out to the maintainer on discord.

Ok thanks @Sameerkash

**Comment by vaibhavarora102** [comment]
Merged👍 previous pull request

**Comment by anotherwebguy** [comment]
> Merged👍 previous pull request

Sir plz add the level label there and plz take the points into consideration as i've solved two issues in that pr 
It should be a level 3 issue?
Thanks:) @vaibhavarora102
