### ISSUE TITLE
Readme file enhancement

### ISSUE THREAD

**Issue by anirudhsai20** [CodeFlow201/forestTreesTagging#84]
The Readme file can be enhanced by adding a list of all the Open Source programs in which this project has been listed in.

**Comment by anirudhsai20** [comment]
Hi! Please assign this issue to me under GSSOC.

**Comment by vilsi12** [comment]
Hi sir Can you please assign me

**Comment by anirudhsai20** [comment]
Hi! Kindly check this PR.

**Comment by shraddhavp** [comment]
@hkaur008 would like to work on this issue by adding contributing guidelines in the readme.md file

**Comment by shraddhavp** [comment]
please assign me this issue @hkaur008

**Comment by hkaur008** [comment]
Readme File enhancements are not considered under hacktoberfest , u can pick other issues
