### ISSUE TITLE
Login Screen Renderflex Issue

### ISSUE THREAD

**Issue by Mohitmadhav** [CodeFlow201/forestTreesTagging#87]
### **Describe the bug:**
The bottom overflow issue is there in the Login Page

### **Screenshots:**
![Screenshot_20210424-133545](https://user-images.githubusercontent.com/59333817/115951783-45872580-a500-11eb-919c-70278d891c3f.png)

### **Additional context:**
@ghackg11 @vaibhavarora102 please assign me this issue as a GSSoC participant and add the labels to it.

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by Mohitmadhav** [comment]
@vaibhavarora102 please check my PR

**Comment by Mohitmadhav** [comment]
@Sameerkash can you please check the PR for this issue?

**Comment by vilsijain** [comment]
Can I work for this issue and i am good in ui

**Comment by Mohitmadhav** [comment]
@vilsi12 I already created a PR. The issue is resolved.
Thanks
