### ISSUE TITLE
Google Authentication Through Firebase

### ISSUE THREAD

**Issue by SamarpanCoder2002** [CodeFlow201/forestTreesTagging#9]
I would like to add Google Authentication through Firebase. .... This issue not yet present here......If I can forward with that, Please assign me to here....I am also a **_GSSOC'21_** participant.....Thank you

**Comment by vaibhavarora102** [comment]
@SamarpanCoder2002  this issue looks good to us, you can proceed to add this feature

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002 this issue looks good to us, you can proceed to add this feature

For add this feature, I need to access firebase account related to that project....... If you have already a firebase account, kindly make me collaborator in that firebase account(my gmail:   samarpanofficial2021@gmail.com ).......If you have no firebase account, then I can proceed with making new firebase account....Waiting for your response.....Thank you @vaibhavarora102

**Comment by SamarpanCoder2002** [comment]
> > @SamarpanCoder2002 this issue looks good to us, you can proceed to add this feature
> 
> For add this feature, I need to access firebase account related to that project....... If you have already a firebase account, kindly make me collaborator in that firebase account(my gmail: [samarpanofficial2021@gmail.com](mailto:samarpanofficial2021@gmail.com) ).......If you have no firebase account, then I can proceed with making new firebase account....Waiting for your response....Thank you

**Comment by ghackg11** [comment]
@SamarpanCoder2002 hey, we actually don't need Google authentication in our app. We are planning to have a specific login signup which will have different type of users and we will update about it soon.So you can close this issue for now.

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002 hey, we actually don't need Google authentication in our app. We are planning to have a specific login signup which will have different type of users and we will update about it soon.So you can close this issue for now.

Ok as your wish @ghackg11 .... So, Can I introduce Email and password authentication with raise a new issue or not? Please let me know @ghackg11 @vaibhavarora102

**Comment by ghackg11** [comment]
Yes you can do that, that would be a necessary one for any kind of authentication process.

**Comment by SamarpanCoder2002** [comment]
> Yes you can do that, that would be a necessary one for any kind of authentication process.

Ok....I close that issue and raise an new issue about email and password verification...Hope you assign me @ghackg11

**Comment by ghackg11** [comment]
@SamarpanCoder2002 sure:)

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002 sure:)

hello @ghackg11, @vaibhavarora102 , I  already added email and password issue with issue(#19 )...Please Take a look here...
